# Generated by Django 2.2.1 on 2019-07-03 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190701_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Courses')),
            ],
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='name',
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='semester',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Department'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Faculties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Faculties'),
        ),
        migrations.AddField(
            model_name='courses',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Department'),
        ),
        migrations.AddField(
            model_name='courses',
            name='Faculties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Faculties'),
        ),
        migrations.AddField(
            model_name='department',
            name='Faculties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Faculties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloads',
            name='Courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Courses'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='Faculties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Faculties'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='Semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Semester'),
        ),
    ]
