# Generated by Django 2.2.1 on 2019-07-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190703_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='downloads',
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='Courses',
            new_name='Course',
        ),
        migrations.AlterField(
            model_name='faculties',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
