# Generated by Django 2.2.1 on 2019-07-03 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190703_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='faculties',
            old_name='name',
            new_name='faculties_name',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='name',
            new_name='semester_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Faculties',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Faculties',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='Faculties',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='Semester',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Faculties',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculties'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faculties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloads',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='faculties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculties'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.semester'),
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course'),
        ),
        migrations.AddField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='semester',
            name='faculties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculties'),
        ),
    ]
