# Generated by Django 2.2.1 on 2019-07-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190703_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='faculties',
            new_name='faculties_id',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='id',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='downloads',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='downloads',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='downloads',
            old_name='faculties',
            new_name='faculties_id',
        ),
        migrations.RenameField(
            model_name='downloads',
            old_name='semester',
            new_name='semester_id',
        ),
        migrations.RenameField(
            model_name='faculties',
            old_name='id',
            new_name='faculties_id',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='faculties',
            new_name='faculties_id',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='id',
            new_name='semester_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='faculties',
        ),
        migrations.AddField(
            model_name='department',
            name='faculties_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faculties'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', to_field='id'),
        ),
        migrations.AlterField(
            model_name='course',
            name='faculties_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculties', to_field='id'),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', to_field='id'),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='faculties_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculties', to_field='id'),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='semester_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.semester', to_field='id'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course', to_field='id'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', to_field='id'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='faculties_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculties', to_field='id'),
        ),
    ]
